services:
  # Backend service
  - type: web
    name: morphy-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    customDomains:
      - morphyimg.ovh
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://morphyimg.com
      - key: DATABASE_URL
        value: postgresql://admin:YOUR_PASSWORD@gs32813-001.eu.clouddb.ovh.net:35185/admin
      - key: DB_HOST
        value: gs32813-001.eu.clouddb.ovh.net
      - key: DB_PORT
        value: "35185"
      - key: DB_NAME
        value: admin
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: YOUR_PASSWORD
      - key: DB_SSL
        value: "true"
    healthCheckPath: /health

  # Frontend service
  - type: web
    name: morphy-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    customDomains:
      - morphyimg.com
    envVars:
      - key: VITE_API_BASE_URL
        value: https://morphyimg.ovh
      - key: VITE_API_BASE_URL_FALLBACK
        value: https://morphy-2-n2tb.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html