services:
  # Backend service
  - type: web
    name: morphy-2-n2tb
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    customDomains:
      - morphyimg.ovh
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://morphyimg.com
      - key: FRONTEND_URL_ALT
        value: https://morphy-1-ulvv.onrender.com
      - key: DATABASE_URL
        value: postgresql://admin:3fEsjBBcw4uUPtzca5@gs32813-001.eu.clouddb.ovh.net:35185/admin
      - key: DB_HOST
        value: gs32813-001.eu.clouddb.ovh.net
      - key: DB_PORT
        value: "35185"
      - key: DB_NAME
        value: admin
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: 3fEsjBBcw4uUPtzca5
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        value: AC9JIdLTgX48ASC70C9HJR4Q4YLWaNyQPMnxD9s/obY=
      - key: SESSION_SECRET
        value: 0334b2c8d3484021ca3f495e3da23cd9f7c1cedd
      - key: MAX_FILE_SIZE
        value: "104857600"
      - key: MAX_BATCH_SIZE
        value: "104857600"
      - key: MAX_FILES_PER_BATCH
        value: "20"
    healthCheckPath: /health

  # Frontend service
  - type: web
    name: morphy-1-ulvv
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    customDomains:
      - morphyimg.com
    envVars:
      - key: VITE_API_BASE_URL
        value: https://morphyimg.ovh
      - key: VITE_API_BASE_URL_FALLBACK
        value: https://morphy-2-n2tb.onrender.com