name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FRONTEND_VPS_SSH_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan ${{ secrets.FRONTEND_VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Try connecting to VPS
        env:
          VPS_HOST: ${{ secrets.FRONTEND_VPS_HOST }}
          VPS_USER: ${{ secrets.FRONTEND_VPS_USERNAME }}
        run: ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "hostname && whoami && uptime"


